- name: Evaluate User Workload Monitoring
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: absent
    kind: ConfigMap
    api_version: v1
    definition:
      metadata:
        name: cluster-monitoring-config
        namespace: openshift-monitoring

- name: Delete Namespace {{ grafana_project }}
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: absent
    kind: Project
    api_version: project.openshift.io/v1
    definition:
      metadata:
        name: "{{ grafana_project }}"
        annotations:
          openshift.io/description: "Project for monitoring dashboard"
          openshift.io/display-name: "RHI Demo Grafana"
