- name: Provision User Monitoring
  ansible.builtin.include_tasks: provision_monitoring.yml
  when:
    - enable_user_workload_monitoring
    - not delete_demo

- name: Configure User Monitoring
  ansible.builtin.include_tasks: configure_monitoring.yml
  when:
    - enable_user_workload_monitoring
    - not delete_demo

- name: Delete Monitoring
  ansible.builtin.include_tasks: delete_monitoring.yml
  when: delete_demo | bool
