- name: Evaluate User Workload Monitoring
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: no
    state: present
    kind: ConfigMap
    api_version: v1
    definition:
      metadata:
        name: cluster-monitoring-config
        namespace: openshift-monitoring
      data:
        config.yaml: |
          enableUserWorkload: true

- name: Evaluate {{ grafana_project }} Namespace
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: no
    state: present
    kind: Project
    api_version: project.openshift.io/v1
    definition:
      metadata:
        name: "{{ grafana_project }}"
        annotations:
          openshift.io/description: "Project for monitoring dashboard"
          openshift.io/display-name: "{{ grafana_project_name }}"

- name: Evaluate Operator Group
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: no
    state: present
    api_version: operators.coreos.com/v1
    kind: OperatorGroup
    definition:
      metadata:
        name: '{{ grafana_project }}-operatorgroup'
        namespace: '{{ grafana_project}}'
      spec:
        targetNamespaces:
        - '{{ grafana_project }}'

- name: Evaluate Grafana Operator
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: no
    state: present
    kind: Subscription
    api_version: operators.coreos.com/v1alpha1
    definition:
      metadata:
        name: grafana-operator
        namespace: '{{ grafana_project }}'
      spec:
        channel: v4
        installPlanApproval: Automatic
        name: grafana-operator
        source: community-operators
        sourceNamespace: openshift-marketplace

- name: Wait Grafana Operator
  k8s_info:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: no
    api_version: v1
    kind: Pod
    namespace: '{{ grafana_project }}'
    label_selectors:
      - control-plane = controller-manager
    field_selectors:
      - status.phase=Running
  register: r_grafana_pod
  retries: 20
  delay: 10
  until: r_grafana_pod.resources | list | length == 1

- name: Evaluate Grafana Cluster Files
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: no
    state: present
    resource_definition: "{{ lookup('file', item ) }}"
  loop:
    - grafana_cluster_role.yml

- name: Evaluate Grafana Files
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: no
    state: present
    namespace: '{{ grafana_project }}'
    resource_definition: "{{ lookup('file', item ) }}"
  loop:
    - grafana_sa.yml
    - grafana_session_secret.yml
    - grafana_cm.yml

- name: Evaluate Grafana Templates
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: no
    state: present
    namespace: '{{ grafana_project }}'
    resource_definition: "{{ lookup('template', item ) }}"
  loop:
    -  grafana_binding.yml.j2
    -  grafana_instance.yml.j2
  #  -  grafana_oauth.yml.j2

- name: Wait Grafana Instance
  k8s_info:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: no
    api_version: v1
    kind: Pod
    namespace: '{{ grafana_project }}'
    label_selectors:
      - app = grafana
    field_selectors:
      - status.phase=Running
  register: r_grafana_pod
  retries: 20
  delay: 10
  until: r_grafana_pod.resources | list | length == 1
