- name: Evaluate project {{ cicd_project }}
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: present
    kind: Project
    api_version: project.openshift.io/v1
    definition:
      metadata:
        name: "{{ cicd_project }}"
        annotations:
          openshift.io/description: ""
          openshift.io/display-name: ""

- name: Evalute Pipeline ServiceAccount Permissions
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: present
    api_version: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    definition:
      metadata:
        name: pipeline-edit
        namespace: '{{ demo_project }}'
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: edit
      subjects:
        - kind: ServiceAccount
          name: pipeline
          namespace: '{{ cicd_project }}'

- name: Evaluate quay-secret
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: present
    resource_definition: "{{ lookup('template', 'secret_quay.yml.j2') }}"

- name: Evaluate ArgoCD Secret for Pipelines
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: present
    kind: Secret
    api_version: v1
    definition:
      metadata:
        name: argocd-env-secret
        namespace: '{{ cicd_project }}'
      stringData:
        ARGOCD_USERNAME: admin
        ARGOCD_PASSWORD: '{{ argo_password }}'
        ARGOCD_SERVER: openshift-gitops-server.openshift-gitops
      type: Opaque

- name: Evaluate PVCs
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: present
    resource_definition: "{{ lookup('template', 'tekton_pvcs.yml.j2') }}"

- name: Evaluate buildah Task
  retries: 5
  delay: 20
  register: result
  until:
    - result.failed == false
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: present
    resource_definition: "{{ lookup('template', 'tekton_task_buildah.yml.j2') }}"

- name: Evaluate maven-version Task
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: present
    resource_definition: "{{ lookup('template', 'tekton_task_maven_version.yml.j2') }}"

- name: Evaluate argo-sync Task
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: present
    resource_definition: "{{ lookup('template', 'tekton_task_argo.yml.j2') }}"

- name: Evaluate iDaaS Connect Pipelines
  retries: 5
  delay: 10
  register: result
  until:
    - result.failed == false
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: present
    resource_definition: "{{ lookup('template', 'tekton_pipeline.yml.j2') }}"
  loop: '{{ idaas_connect_components }}'
