- name: Provision AMQ Streams
  ansible.builtin.include_tasks: provision.yml
  when:
    - not delete_demo

# - name: Configure AMQ Streams
#   ansible.builtin.include_tasks: configure.yml
#   when:
#   - not delete_demo

# - name: Delete Monitoring
#   ansible.builtin.include_tasks: delete.yml
#   when: delete_demo | bool
