- name: Evaluate {{ demo_project }} Namespace
  k8s:
    state: present
    kind: Project
    api_version: project.openshift.io/v1
    definition:
      metadata:
        name: "{{ demo_project }}"

- name: Evaluate Operator Group
  when: not delete_demo
  k8s:
    state: present
    api_version: operators.coreos.com/v1
    kind: OperatorGroup
    definition:
      metadata:
        name: '{{ demo_project }}-operatorgroup'
        namespace: '{{ demo_project}}'
      spec:
        targetNamespaces:
        - '{{ demo_project }}'

- name: Evaluate AMQ Streams Operator
  k8s:
    state: present
    kind: Subscription
    api_version: operators.coreos.com/v1alpha1
    definition:
      metadata:
        name: amq-streams
        namespace: '{{ demo_project }}'
      spec:
        channel: stable
        installPlanApproval: Automatic
        name: amq-streams
        source: redhat-operators
        sourceNamespace: openshift-marketplace

- name: Waiting for AMQ Streams operator to install
  shell: set -o pipefail && oc get csv -n {{ demo_project }} | grep amqstreams
  register: install_status
  until: "'Succeeded' in install_status.stdout"
  retries: 20
  delay: 15
  args:
    executable: /bin/bash

- name: Evaluate Cluster ConfigMap
  k8s:
    state: present
    namespace: '{{ demo_project }}'
    resource_definition: "{{ lookup('file', 'metrics-cm.yml') }}"


- name: Evaluate Cluster Instance
  k8s:
    state: present
    namespace: '{{ demo_project }}'
    name: '{{ kafka_cluster_name }}'
    resource_definition: "{{ lookup('file', 'cluster.yml') }}"

- name: Waiting for Cluster instance to be ready
  shell: set -o pipefail && oc get kafka -n {{ demo_project }} | grep {{ kafka_cluster_name }}
  register: install_status
  until: "'True' in install_status.stdout"
  retries: 20
  delay: 15
  args:
    executable: /bin/bash
