- name: Deploy iDaaS Connect
  hosts: localhost
  vars:
    demo_delete: false
    demo_project: idaas
    demo_project_description: Namespace for iDaaS Connect components
    cicd_project: idaas-cicd
    grafana_project: idaas-grafana
    grafana_project_name: iDaaS Grafana
    grafana_user: root
    grafana_password: secret
    insecure_skip_tls_verify: true
    enable_logging: true
    enable_user_workload_monitoring: true
    delete_demo: false
    argo_admin_user: opentlc-mgr
    idaas_connect_git: https://github.com/Project-Herophilus/iDaaS-Connect.git
    idaas_connect_gitops_git: https://github.com/Project-Herophilus/idaas-connect-gitops.git
    image_registry_url: quay.io/redhathealthcare
    enable_pipelines: true
    idaas_connect_components:
      - hl7
      - fhir
      - edi
  tasks:

    - name: Check Parameters
      ansible.builtin.fail:
        msg: "This play requires 'server', 'token' and 'docker_config' to be defined"
      when: >-
       (server is undefined) or (token is undefined) or (docker_config is undefined) or
       (server | length == 0) or (token | length == 0) or (docker_config | length == 0)

    - name: Set domain
      ansible.builtin.set_fact:
        domain: "{{ server | regex_replace('https://api.') | regex_replace(':6443') }}"

    - name: Evaluate Namespace {{ demo_project }}
      kubernetes.core.k8s:
        api_key: '{{ token }}'
        host: '{{ server }}'
        validate_certs: false
        state: present
        kind: Namespace
        api_version: v1
        definition:
          metadata:
            name: "{{ demo_project }}"
            annotations:
              openshift.io/description: "{{ demo_project_description }}"
              openshift.io/display-name: "{{ demo_project }}"

    - name: Include Logging role
      ansible.builtin.include_role:
        name: logging

    - name: Include Monitoring role
      ansible.builtin.include_role:
        name: monitoring

    - name: Include ArgoCD role
      ansible.builtin.include_role:
        name: argocd

    - name: Include Tekton role
      ansible.builtin.include_role:
        name: tekton

    - name: Include AMQ Streams role
      ansible.builtin.include_role:
        name: streams
