- name: Evaluate cluster-admins group
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: present
    api_version: user.openshift.io/v1
    kind: Group
    definition:
      metadata:
        name: cluster-admins
      users:
        - '{{ argo_admin_user }}'

- name: Evaluate GitOps Permissions
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: present
    api_version: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    definition:
      metadata:
        name: edit-0
        namespace: '{{ demo_project }}'
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: edit
      subjects:
        - kind: ServiceAccount
          name: openshift-gitops-argocd-application-controller
          namespace: openshift-gitops

- name: Evaluate GitOps Project
  retries: 5
  delay: 20
  register: result
  until:
    - result.failed == false
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: present
    resource_definition: "{{ lookup('template', 'argo_project.yml.j2') }}"

- name: Evaluate GitOps Application
  retries: 5
  delay: 20
  register: result
  until:
    - result.failed == false
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: present
    resource_definition: "{{ lookup('template', 'argo_app.yml.j2') }}"
  loop: '{{ idaas_connect_components }}'

- name: Get openshift-gitops-cluster Secret
  kubernetes.core.k8s_info:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    kind: Secret
    name: openshift-gitops-cluster
    namespace: openshift-gitops
    api_version: v1
  register: r_gitops_secret
  until:
    - r_gitops_secret.resources is defined
    - r_gitops_secret.resources[0].data['admin.password'] is defined
  retries: 10
  delay: 15

- name: Set argo_password
  ansible.builtin.set_fact:
    argo_password: "{{ r_gitops_secret.resources[0].data['admin.password'] | b64decode }}"


- name: Test ArgoCD API Service
  ansible.builtin.uri:
    url: https://openshift-gitops-server-openshift-gitops.apps.{{ domain }}
    validate_certs: false
    method: GET
  register: result
  until: result.status == 200
  retries: 10
  delay: 15

- name: Get ArgoCD token
  ansible.builtin.uri:
    url: https://openshift-gitops-server-openshift-gitops.apps.{{ domain }}/api/v1/session
    validate_certs: false
    method: POST
    headers:
      Content-Type: application/json
    body: "{{ lookup('template', 'argo_authentication.json.j2') }}"
    body_format: json
    status_code: 200,201,204
  register: r_argo_token

- name: Set argo_token
  ansible.builtin.set_fact:
    argo_token: "{{ r_argo_token.json.token }}"

- name: Sync Apps
  ansible.builtin.uri:
    url: https://openshift-gitops-server-openshift-gitops.apps.{{ domain }}/api/v1/applications/idaas-connect-{{ item }}/sync
    validate_certs: false
    method: POST
    headers:
      Authorization: Bearer {{ argo_token }}
    status_code: 200
  register: r_argo_token
  loop: '{{ idaas_connect_components }}'
