- name: Provision GitOps
  ansible.builtin.include_tasks: provision_gitops.yml
  when: not delete_demo

- name: Configure GitOps
  ansible.builtin.include_tasks: configure_gitops.yml
  when: not delete_demo

- name: Delete GitOps
  ansible.builtin.include_tasks: delete_gitops.yml
  when: delete_demo | bool
