- name: Evaluate OpenShift GitOps Subscription
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: no
    state: present
    kind: Subscription
    api_version: operators.coreos.com/v1alpha1
    definition:
      metadata:
        name: openshift-gitops-operator
        namespace: openshift-operators
      spec:
        channel: stable
        installPlanApproval: Automatic
        name: openshift-gitops-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace

- name: Wait Gitops Operator
  k8s_info:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: no
    api_version: v1
    kind: Pod
    namespace: openshift-operators
    label_selectors:
      - control-plane = controller-manager
    field_selectors:
      - status.phase=Running
  register: r_gitops_pod
  retries: 20
  delay: 10
  until: r_gitops_pod.resources | list | length == 1
